# Generated by Django 4.2.7 on 2023-11-30 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('class_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('subject_name', models.CharField(max_length=250)),
                ('semister', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('file_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('path', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('role_id', models.AutoField(primary_key=True, serialize=False)),
                ('role', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('u_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('u_name', models.CharField(max_length=100)),
                ('u_email', models.EmailField(max_length=100, unique=True)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.role')),
            ],
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('content_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('content_jason', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.file')),
            ],
        ),
    ]
