# Generated by Django 4.2.7 on 2023-11-30 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='email',
            new_name='u_email',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='uname',
            new_name='u_name',
        ),
        migrations.AlterField(
            model_name='content',
            name='file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.file'),
        ),
    ]
